// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcjiltlurzvuzhuhjzjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjamlsdGx1cnp2dXpodWhqempkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NjQzNzMsImV4cCI6MjA3NDQ0MDM3M30.8VNCebCoJfZ9rfLd65WxEwy8niOGhGA5-jqr_HkSWU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});